- hosts: localhost
  roles:
    - createVM

- hosts: localhost
  tasks:
  - name: Add Ansible Repo
    become: yes
    apt_repository: repo=ppa:ansible/ansible

  - name: Install Ansible
    become: yes
    apt: name={{item}} update_cache=yes
    with_items:
    - ansible
    - python-netaddr

  - name: Install Roles
    command: ansible-galaxy install -r requirements.yml