Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]
    vb.memory = 750
  end

  config.vm.define :server do |machine|
    machine.vm.network 'private_network', ip: '192.168.33.14'
  end

  config.vm.define :nomad1 do |machine|
    machine.vm.network 'private_network', ip: '192.168.33.11'
  end

  config.vm.define :nomad2 do |machine|
    machine.vm.network 'private_network', ip: '192.168.33.12'
  end

  config.vm.define :nomad3 do |machine|
    machine.vm.network 'private_network', ip: '192.168.33.13'
  end

end