---
- hosts: localhost
  become: true
  vars:
    home_path: "/home/ubuntu/trial1"
    jenkins:
      url_username: "mkd_test1"
      url_password: "mkd_test_passwd_1"
      url: "http://localhost:8080"
      validate_certs: no
  tasks:
    - name: Check Who Am I
      shell: whoami
 
    - name: Install Prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
        - maven
 
    - name: Add Oracle Repository
      apt_repository:
        repo: 'ppa:webupd8team/java'
 
    - name: Accept Oracle License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
 
    - name: Install Java-8
      apt:
        name: oracle-java8-installer    
        state: present
        update_cache: yes
 
    - name: Add Jenkins Repository Key
      apt_key:
        url: "https://jenkins-ci.org/debian/jenkins-ci.org.key"
        state: present
        validate_certs: no
 
    - name: Adding Jenkins Source List
      shell: echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list
 
    - name: Install Jenkins
      apt:
        name: jenkins    
        state: present
        update_cache: yes
 
    - name: Disable security in config file
      copy:
        src: "demo-config.xml"
        dest: "/var/lib/jenkins/config.xml"
 
    - name: Enable the firewall
      ufw: 
        state: enabled
        policy: allow
      become: yes
 
    - name: Open port 8080
      ufw: 
        rule: allow
        port: 8080
      become: yes

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Wait for restart
      uri:
        url: "http://localhost:8080/cli/"
        status_code: 200
      register: restart
      until: restart.status == 200
      retries: 10
      delay: 10

    - name: Create Groovy Directory
      file:
        path: "/var/lib/jenkins/init.groovy.d"
        state: directory
        mode: 0777
 
    - name: Copy User-Creation Script
      copy:
        src: "jenkins_script.groovy"
        dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
        mode: 0777
     
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Wait for restart
      uri:
        url: "http://localhost:8080/cli/"
        status_code: 403
      register: restart
      until: restart.status == 403
      retries: 10
      delay: 10
 
    - name: Removing User-Creation Script
      file:
        path: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
        state: absent
 
    - name: Downloading Jenkins CLI Jar
      get_url:
        url: "http://localhost:8080/jnlpJars/jenkins-cli.jar"
        dest: "{{ home_path }}"
        mode: 0775
 
    - name: Install Jenkin Plugins
      jenkins_plugin:
        name: "{{ item }}"
        params: "{{ jenkins }}"
      with_items:
        - maven-plugin
        - github
        - jacoco
        - junit
        - test-stability
        - postbuildscript
        - build-timeout
 
    - name: Checking Jenkins State
      service:
        name: jenkins
        state: started
