- name: "Installing mysql"
  apt: package="mysql-server" state="present"
  environment:
    DEBIAN_FRONTEND=noninteractive
  become: yes

- name: Changing mySQL plugin to use password
  shell: "mysql -u root -e \"USE mysql; UPDATE user SET plugin=\'mysql_native_password\' WHERE User=\'root\'; FLUSH PRIVILEGES;\""
  become: true

- name: Allow access from all IPs
  shell: "mysql -u root -e \"GRANT ALL PRIVILEGES ON *.* TO \'root\'@\'%\' WITH GRANT OPTION; FLUSH PRIVILEGES;\""
  
- name: "Disable Case Sensitivity and increase connections"
  template: src=sql_template.cnf.j2 dest={{ mysql_location }}/mysqld.cnf
  become: yes

- name: "Restart mysql service"
  service: name=mysql state=restarted
  become: yes