- name: "Check whether path exists"
  file: path={{ apacheDeployLocation }} state=directory
  become: yes

- debug: 
    var: iTrustTempLocation

- name: "Deploying war file to tomcat"
  unarchive:
    src: "{{iTrustTempLocation}}/iTrust/target/iTrust-23.0.0.war"
    dest: "{{ apacheDeployLocation }}"
  become: yes
